/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * configurable-http-proxy routing table (see configurable-http-proxy docs for details)
 */
export type GetProxy200 = { [key: string]: unknown };
