/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { PaginationOffsetParameter } from "./paginationOffsetParameter";
import type { PaginationLimitParameter } from "./paginationLimitParameter";

export type GetServicesParams = {
  /**
 * Return a number of results, starting at the specified offset.
Can be used with limit to paginate.
If unspecified, return all items.

 */
  offset?: PaginationOffsetParameter;
  /**
 * Return a finite number of results.
Can be used with offset to paginate.
If unspecified, use api_page_default_limit.

 */
  limit?: PaginationLimitParameter;
};
