/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { PaginatedList } from "./paginatedList";
import type { GetSharesServer200AllOf } from "./getSharesServer200AllOf";

export type GetSharesServer200 = PaginatedList & GetSharesServer200AllOf;
