/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { GetUsersState } from "./getUsersState";
import type { PaginationOffsetParameter } from "./paginationOffsetParameter";
import type { PaginationLimitParameter } from "./paginationLimitParameter";

export type GetUsersParams = {
  /**
 * Return only users who have servers in the given state.
If unspecified, return all users.

active: all users with any active servers (ready OR pending)
ready: all users who have any ready servers (running, not pending)
inactive: all users who have *no* active servers (complement of active)

Added in JupyterHub 1.3

 */
  state?: GetUsersState;
  /**
 * Return a number of results, starting at the specified offset.
Can be used with limit to paginate.
If unspecified, return all items.

 */
  offset?: PaginationOffsetParameter;
  /**
 * Return a finite number of results.
Can be used with offset to paginate.
If unspecified, use api_page_default_limit.

 */
  limit?: PaginationLimitParameter;
  /**
 * Include stopped servers in user model(s).
Added in JupyterHub 3.0.
Allows retrieval of information about stopped servers,
such as activity and state fields.

 */
  include_stopped_servers?: boolean;
  /**
 * Sort users by this key (new in JupyterHub 5.0).
Default: `id` (opaque but stable internal order).
Supported fields: `id`, `name`, `last_activity`.
Results will be in ascending order.
Descending order can be requested with a `-` prefix,
e.g. `sort=-last_activity` for most recently active users first.

 */
  sort?: string;
};
