/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

export type GetUsersState = (typeof GetUsersState)[keyof typeof GetUsersState];

export const GetUsersState = {
  inactive: "inactive",
  active: "active",
  ready: "ready",
} as const;
