/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * Group properties (a dictionary).

Unused by JupyterHub itself,
but an extension point to store information about groups.

Added in JupyterHub 3.2.

 */
export type GroupProperties = { [key: string]: unknown };
