/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * Return a finite number of results.
Can be used with offset to paginate.
If unspecified, use api_page_default_limit.

 */
export type PaginationLimitParameter = number;
