/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { PaginationNext } from "./paginationNext";

/**
 * page info for paginated endpoints
 */
export interface Pagination {
  /** total number of results for the query */
  total?: number;
  /** the maximum number of results */
  limit?: number;
  /** the starting point for this */
  offset?: number;
  /** fields for the next page, if any.
Null if this is the last page.
 */
  next?: PaginationNext;
}
