/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * fields for the next page, if any.
Null if this is the last page.

 */
export type PaginationNextAnyOf = {
  /** the offset for the next page */
  offset?: number;
  /** the same as the above limit, for consistency */
  limit?: number;
  /** the assembled url for the next page,
with query parameters already included.
 */
  url?: string;
};
