/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

export type PatchSharesServerBody = {
  /** group to revoke permissions from.
Exactly one of 'user' and 'group' must be specified.
 */
  group?: string;
  /** user to revoke permissions from.
Exactly one of 'user' and 'group' must be specified.
 */
  user?: string;
  /** scopes to revoke.
If no scopes are specified, all permissions are revoked.
 */
  scopes?: string[];
};
