/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

export type PatchProxyBody = {
  /** IP address of the new proxy */
  ip?: string;
  /** Port of the new proxy */
  port?: string;
  /** Protocol of new proxy, if changed */
  protocol?: string;
  /** CONFIGPROXY_AUTH_TOKEN for the new proxy */
  auth_token?: string;
};
