/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { PostShareCode200AllOfFullAcceptUrl } from "./postShareCode200AllOfFullAcceptUrl";

export type PostShareCode200AllOf = {
  /** The share code itself */
  code?: string;
  /** The URL path for accepting the code */
  accept_url?: string;
  /** The full URL for accepting the code,
if JupyterHub.public_url configuration is defined.
 */
  full_accept_url?: PostShareCode200AllOfFullAcceptUrl;
};
