/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

export type PostShareCodeBody = {
  /** expiration in seconds.
If unspecified, expires in one day (86400)
 */
  expires_in?: number;
  /** scopes to grant */
  scopes?: string[];
};
