/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

export type PostUserTokensBody = {
  /** lifetime (in seconds) after which the requested token will expire. Omit, or specify null or 0 for no expiration. */
  expires_in?: number;
  /** A note attached to the token for future bookkeeping */
  note?: string;
  /** A list of role names from which to derive scopes.
This is a shortcut for assigning collections of scopes;
Tokens do not retain role assignment.
(Changed in 3.0: roles are immediately resolved to scopes
instead of stored on roles.)
 */
  roles?: string[];
  /** A list of scopes that the token should have.
(new in JupyterHub 3.0).
 */
  scopes?: string[];
};
