/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { PostOauthTokenBodyGrantType } from "./postOauthTokenBodyGrantType";

export type PostOauthTokenBody = {
  /** The client id */
  client_id: string;
  /** The client secret */
  client_secret: string;
  /** The grant type (always 'authorization_code') */
  grant_type: PostOauthTokenBodyGrantType;
  /** The code provided by the authorization redirect */
  code: string;
  /** The redirect url */
  redirect_uri: string;
};
