/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * The full URL for accepting the code,
if JupyterHub.public_url configuration is defined.

 */
export type PostShareCode200AllOfFullAcceptUrl = string | null;
