/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { RequestIdentityAllOf } from "./requestIdentityAllOf";
import type { RequestIdentityAllOfTwo } from "./requestIdentityAllOfTwo";

/**
 * The model for the entity making the request.
Extends User or Service model to add information about the specific credentials (e.g. session or token-authorised scopes).

 */
export type RequestIdentity = RequestIdentityAllOf & RequestIdentityAllOfTwo;
