/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * The id of the token authorizing the request, if any.
This id can be used to revoke the token via the API.
Null if the request is not authorized with a token.

Added in 5.0.

 */
export type RequestIdentityAllOfTwoTokenId = string | null;
