/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { RequestIdentityAllOfTwoKind } from "./requestIdentityAllOfTwoKind";
import type { RequestIdentityAllOfTwoSessionId } from "./requestIdentityAllOfTwoSessionId";
import type { RequestIdentityAllOfTwoTokenId } from "./requestIdentityAllOfTwoTokenId";

export type RequestIdentityAllOfTwo = {
  /** 'user' or 'service' depending on the entity which owns the token
   */
  kind?: RequestIdentityAllOfTwoKind;
  /** The session id associated with the request's OAuth token, if any.
null, if the request token not associated with a session id.

Added in 2.0.
 */
  session_id?: RequestIdentityAllOfTwoSessionId;
  /** The list of all expanded scopes the request credentials have access to.

Added in 2.0.
 */
  scopes?: string[];
  /** The id of the token authorizing the request, if any.
This id can be used to revoke the token via the API.
Null if the request is not authorized with a token.

Added in 5.0.
 */
  token_id?: RequestIdentityAllOfTwoTokenId;
};
