/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * The currently pending action, if any.
A server is not ready if an action is pending.

 */
export type ServerPending = (typeof ServerPending)[keyof typeof ServerPending];

export const ServerPending = {
  spawn: "spawn",
  stop: "stop",
} as const;
