/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { SharedServerFullUrl } from "./sharedServerFullUrl";
import type { SharedServerUser } from "./sharedServerUser";

/**
 * Subset of Server model present in Share responses
 */
export interface SharedServer {
  /** the server name. '' for the default server. */
  name?: string;
  /** the server's URL (path only when not using subdomains) */
  url?: string;
  /** The full URL of the server (`https://hub.example.org/user/:name/:servername`).
`null` unless JupyterHub.public_url or subdomains are configured.
 */
  full_url?: SharedServerFullUrl;
  /** whether the server is ready */
  ready?: boolean;
  /** the server's owner */
  user?: SharedServerUser;
}
