/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * When the share code will expire,
always in the future.
`null` if the code does not expire.

 */
export type ShareCodeExpiresAt = string | null;
