/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

export type DeleteShareCodeParams = {
  /**
   * the share code to revoke
   */
  code?: string;
  /**
   * the id of the share code to revoke
   */
  id?: string;
};
