/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { GetInfo200Authenticator } from "./getInfo200Authenticator";
import type { GetInfo200Spawner } from "./getInfo200Spawner";

export type GetInfo200 = {
  /** The version of JupyterHub itself */
  version?: string;
  /** The Python version, as returned by sys.version */
  python?: string;
  /** The path to sys.executable running JupyterHub */
  sys_executable?: string;
  authenticator?: GetInfo200Authenticator;
  spawner?: GetInfo200Spawner;
};
