/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

export type GetInfo200Authenticator = {
  /** The Python class currently active for JupyterHub Authentication */
  class?: string;
  /** The version of the currently active Authenticator */
  version?: string;
};
