/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

export type GetInfo200Spawner = {
  /** The Python class currently active for spawning single-user notebook servers */
  class?: string;
  /** The version of the currently active Spawner */
  version?: string;
};
