/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

export type GetOauthAuthorizeParams = {
  /**
   * The client id
   */
  client_id: string;
  /**
   * The response type (always 'code')
   */
  response_type: string;
  /**
   * A state string
   */
  state?: string;
  /**
   * The redirect url
   */
  redirect_uri: string;
};
