/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { PaginatedList } from "./paginatedList";
import type { GetSharesOwner200AllOf } from "./getSharesOwner200AllOf";

export type GetSharesOwner200 = PaginatedList & GetSharesOwner200AllOf;
