/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * Always the string 'group'
 */
export type GroupKind = (typeof GroupKind)[keyof typeof GroupKind];

export const GroupKind = {
  group: "group",
} as const;
