/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * Return a number of results, starting at the specified offset.
Can be used with limit to paginate.
If unspecified, return all items.

 */
export type PaginationOffsetParameter = number;
