/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { PaginationNextAnyOf } from "./paginationNextAnyOf";

/**
 * fields for the next page, if any.
Null if this is the last page.

 */
export type PaginationNext = PaginationNextAnyOf | null;
