/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { PaginatedListItemsItem } from "./paginatedListItemsItem";
import type { Pagination } from "./pagination";

export interface PaginatedList {
  items?: PaginatedListItemsItem[];
  _pagination?: Pagination;
}
