/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

export type PatchUserBody = {
  /** the new name (optional, if another key is updated i.e. admin) */
  name?: string;
  /** update admin (optional, if another key is updated i.e. name) */
  admin?: boolean;
};
