/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { ShareCode } from "./shareCode";
import type { PostShareCode200AllOf } from "./postShareCode200AllOf";

export type PostShareCode200 = ShareCode & PostShareCode200AllOf;
