/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * Activity for a single server.

 */
export type PostUserActivityBodyServersServerName = {
  /** Timestamp of last-seen activity on this server.
   */
  last_activity: string;
};
