/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

export type PostOauthToken200 = {
  /** The new API token for the user */
  access_token?: string;
  /** Will always be 'Bearer' */
  token_type?: string;
};
