/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

export type PostUsersBody = {
  /** list of usernames to create on the Hub */
  usernames?: string[];
  /** whether the created users should be admins */
  admin?: boolean;
};
