/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { PostUserActivityBodyServers } from "./postUserActivityBodyServers";

export type PostUserActivityBody = {
  /** Timestamp of last-seen activity for this user.
Only needed if this is not activity associated
with using a given server.
 */
  last_activity?: string;
  /** Register activity for specific servers by name.
The keys of this dict are the names of servers.
The default server has an empty name ('').
 */
  servers?: PostUserActivityBodyServers;
};
