/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { PostUserActivityBodyServersServerName } from "./postUserActivityBodyServersServerName";

/**
 * Register activity for specific servers by name.
The keys of this dict are the names of servers.
The default server has an empty name ('').

 */
export type PostUserActivityBodyServers = {
  /** Activity for a single server.
   */
  "<server name>"?: PostUserActivityBodyServersServerName;
};
