/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * The grant type (always 'authorization_code')
 */
export type PostOauthTokenBodyGrantType =
  (typeof PostOauthTokenBodyGrantType)[keyof typeof PostOauthTokenBodyGrantType];

export const PostOauthTokenBodyGrantType = {
  authorization_code: "authorization_code",
} as const;
