/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

export type PostSharesServerBody = {
  /** group to grant permissions to.
Exactly one of 'user' and 'group' can be specified.
 */
  group?: string;
  /** user to grant permissions to.
Exactly one of 'user' and 'group' can be specified.
 */
  user?: string;
  /** scopes to grant */
  scopes?: string[];
};
