/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * 'user' or 'service' depending on the entity which owns the token

 */
export type RequestIdentityAllOfTwoKind =
  (typeof RequestIdentityAllOfTwoKind)[keyof typeof RequestIdentityAllOfTwoKind];

export const RequestIdentityAllOfTwoKind = {
  user: "user",
  service: "service",
} as const;
