/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * The session id associated with the request's OAuth token, if any.
null, if the request token not associated with a session id.

Added in 2.0.

 */
export type RequestIdentityAllOfTwoSessionId = string | null;
