/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * Additional information a deployment can attach to a service.
JupyterHub does not use this field.

 */
export type ServiceInfo = { [key: string]: unknown };
