/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { ServiceKind } from "./serviceKind";
import type { ServiceInfo } from "./serviceInfo";

export interface Service {
  /** The service's name */
  name?: string;
  /** the string 'service' to distinguish from 'user' */
  kind?: ServiceKind;
  /** Whether the service is an admin */
  admin?: boolean;
  /** The names of roles this service has */
  roles?: string[];
  /** The internal url where the service is running */
  url?: string;
  /** The proxied URL prefix to the service's url */
  prefix?: string;
  /** The PID of the service process (if managed) */
  pid?: number;
  /** The command used to start the service (if managed) */
  command?: string[];
  /** Additional information a deployment can attach to a service.
JupyterHub does not use this field.
 */
  info?: ServiceInfo;
}
