/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { ServerPending } from "./serverPending";
import type { ServerFullUrl } from "./serverFullUrl";
import type { ServerFullProgressUrl } from "./serverFullProgressUrl";
import type { ServerState } from "./serverState";
import type { ServerUserOptions } from "./serverUserOptions";

export interface Server {
  /** The server's name. The user's default server has an empty name ('') */
  name?: string;
  /** Whether the server is ready for traffic.
Will always be false when any transition is pending.
 */
  ready?: boolean;
  /** Whether the server is stopped. Added in JupyterHub 3.0,
and only useful when using the `?include_stopped_servers`
request parameter.
Now that stopped servers may be included (since JupyterHub 3.0),
this is the simplest way to select stopped servers.
Always equivalent to `not (ready or pending)`.
 */
  stopped?: boolean;
  /** The currently pending action, if any.
A server is not ready if an action is pending.
 */
  pending?: ServerPending;
  /** The URL path where the server can be accessed
(typically /user/:name/:server.name/).
Will be a full URL if subdomains are configured.
 */
  url?: string;
  /** The URL path for an event-stream to retrieve events during a spawn.
   */
  progress_url?: string;
  /** The full URL of the server (`https://hub.example.org/user/:name/:servername`).
`null` unless JupyterHub.public_url or subdomains are configured.

Added in 5.0.
 */
  full_url?: ServerFullUrl;
  /** The full URL for the progress events (`https://hub.example.org/hub/api/users/:name/servers/:servername/progress`).
`null` unless JupyterHub.public_url is configured.

Added in 5.0.
 */
  full_progress_url?: ServerFullProgressUrl;
  /** UTC timestamp when the server was last started. */
  started?: string;
  /** UTC timestamp last-seen activity on this server. */
  last_activity?: string;
  /** Arbitrary internal state from this server's spawner. Only available on the hub's users list or get-user-by-name method, and only with admin:users:server_state scope. None otherwise. */
  state?: ServerState;
  /** User specified options for the user's spawned instance of a single-user server. */
  user_options?: ServerUserOptions;
}
