/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { SharedServer } from "./sharedServer";
import type { ShareGroup } from "./shareGroup";
import type { ShareUser } from "./shareUser";

/**
 * A single sharing permission.
There is at most one of these objects per (server, user) or (server, group) combination.

 */
export interface Share {
  /** the server granting shared access */
  server?: SharedServer;
  /** the scopes granted by this Share */
  scopes?: string[];
  /** the group being shared with (exactly one of 'user' or 'group' will be non-null, the other will be null) */
  group?: ShareGroup;
  /** the user being shared with (exactly one of 'user' or 'group' will be non-null, the other will be null) */
  user?: ShareUser;
  /** when the share was first granted */
  created_at?: string;
}
