/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { SharedServer } from "./sharedServer";
import type { ShareCodeExpiresAt } from "./shareCodeExpiresAt";

/**
 * A single sharing code. There is at most one of these objects per (server, user) or (server, group) combination.
 */
export interface ShareCode {
  /** the server granting shared access */
  server?: SharedServer;
  /** the scopes granted by this Share */
  scopes?: string[];
  /** the share-code's id.
Can be used to revoke share codes.
 */
  id?: string;
  /** when the share code was issued */
  created_at?: string;
  /** When the share code will expire,
always in the future.
`null` if the code does not expire.
 */
  expires_at?: ShareCodeExpiresAt;
}
