/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * the group being shared with (exactly one of 'user' or 'group' will be non-null, the other will be null)
 */
export type ShareGroupAnyOf = {
  name?: string;
};
