/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * The session id associated with the token, if any.
Only used for tokens set during oauth flows.

Added in 2.0.

 */
export type TokenSessionId = string | null;
