/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { TokenSessionId } from "./tokenSessionId";

export interface Token {
  /** The id of the API token. Used for modifying or deleting the token. */
  id?: string;
  /** The user that owns a token (undefined if owned by a service) */
  user?: string;
  /** The service that owns the token (undefined of owned by a user) */
  service?: string;
  /** Deprecated in JupyterHub 3, always an empty list. Tokens have 'scopes' starting from JupyterHub 3. */
  roles?: string[];
  /** List of scopes this token has been assigned. New in JupyterHub 3. In JupyterHub 2.x, tokens were assigned 'roles' instead of scopes. */
  scopes?: string[];
  /** A note about the token, typically describing what it was created for. */
  note?: string;
  /** Timestamp when this token was created */
  created?: string;
  /** Timestamp when this token expires. Null if there is no expiry. */
  expires_at?: string;
  /** Timestamp of last-seen activity using this token.
Can be null if token has never been used.
 */
  last_activity?: string;
  /** The session id associated with the token, if any.
Only used for tokens set during oauth flows.

Added in 2.0.
 */
  session_id?: TokenSessionId;
}
