/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * Authentication state of the user. Only available with admin:users:auth_state
scope. None otherwise.

 */
export type UserAuthState = { [key: string]: unknown };
