/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * the string 'user' to distinguish from 'service'
 */
export type UserKind = (typeof UserKind)[keyof typeof UserKind];

export const UserKind = {
  user: "user",
} as const;
