/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */

/**
 * The currently pending action, if any
 */
export type UserPending = (typeof UserPending)[keyof typeof UserPending];

export const UserPending = {
  spawn: "spawn",
  stop: "stop",
} as const;
