/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * JupyterHub REST API
 * The REST API for JupyterHub.
<a href="./">Return to JupyterHub documentation</a>.

 * OpenAPI spec version: 5.3.0
 */
import type { UserKind } from "./userKind";
import type { UserPending } from "./userPending";
import type { UserServers } from "./userServers";
import type { UserAuthState } from "./userAuthState";

export interface User {
  /** The user's name */
  name?: string;
  /** the string 'user' to distinguish from 'service' */
  kind?: UserKind;
  /** Whether the user is an admin */
  admin?: boolean;
  /** The names of roles this user has */
  roles?: string[];
  /** The names of groups where this user is a member */
  groups?: string[];
  /** The user's notebook server's base URL, if running; null if not. */
  server?: string;
  /** The currently pending action, if any */
  pending?: UserPending;
  /** Timestamp of last-seen activity from the user */
  last_activity?: string;
  /** The servers for this user.
By default: only includes _active_ servers.
Changed in 3.0: if `?include_stopped_servers` parameter is specified,
stopped servers will be included as well.
 */
  servers?: UserServers;
  /** Authentication state of the user. Only available with admin:users:auth_state
scope. None otherwise.
 */
  auth_state?: UserAuthState;
}
